
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Rahma",
    "password": "HolaMundo1"
}

###
POST http://localhost:5000/api/auth/login 
Content-Type: application/json

{

"username": "Rahma",
"password": "HolaMundo1" }